### DISCUSSION TITLE
Sxhkd like keybinds

### DISCUSSION THREAD

**Discussion by VuiMuich** [leftwm/leftwm#420] [Ideas]
When recently I was fooling around a little bit with bspwm I really got intrigued by the elegance with which sxhkd is configured and I was thinking if we would like to adopt some aspects of their syntax.
Namely their use of curly brackets might help to make our config.toml tidier and more compact by being less repetitive.

Though this obviously fits well with #292 we might even introduce this in a no breaking way ahead of the big config changes.

Also, this might be a nice opportunity to introduce a `ConfigReload`, that only reloads selected parameters like keybinds and behavior toggles without restarting the worker.

**Comment by lex148** [comment]
It really wouldn't be that big a deal to update the loading of the config to support the format of the end users choosing. We could easily support json,yaml,toml, whatever. As long as serde supports the format it should work.

**Comment by VuiMuich** [comment]
I didn't mean to change away from toml actually, but extend what we could parse it into. But maybe this is just a naive and foolish idea of mine, that wouldn't work properly or would mean just to much work.

Maybe it would help if we ad a something like this:
```toml
[[multi-keybind]]
commands = ["GoToTag", "MoveToTag"]
values = [[1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9]]
modifiers = [["modkey"], ["modkey", "Shift"]]
keys = [[1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9]]

#maybe even try to be smart and deduce, how modifiers and the single given key should be mapped to the commands
[[multi-keybind]]
commands = ["SoftReload", "HardReload"]
modifiers = ["modkey, ["Shift", "Alt"] ]
keys = "r"
```
