### ISSUE TITLE
Border colors

### ISSUE THREAD

**Issue by k3rn3l-st** [leftwm/leftwm#148]
could you add feature to change the color of the borders from an external process to floating, default and focused?

**Comment by lex148** [comment]
I think what you are looking for already exists. 
LeftWM has a linux pipe that can be used to send it commands from almost anything. 
Here is an example:

bash
```bash
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
```
theme.toml
```toml
border_width = 1
margin = 20 
default_border_color = "#222222"
floating_border_color = "#005500"
focused_border_color = "#FFB53A"
```

Let me know if this is what you are looking for. If not then I will see if I can get it added.
