### ISSUE TITLE
Allow user to set default terminal in config

### ISSUE THREAD

**Issue by AethanFoot** [leftwm/leftwm#187]
As the title says, instead of or along with searching for common terminals in path (this also then excludes various terminals such as kitty).

**Comment by mautamu** [comment]
You should be able to set it directly in the configuration file after it is first generated (after first LeftWM startup). The only time default_terminal is called is when first generating a [config.toml file](https://github.com/leftwm/leftwm/blob/eac86e293556e4f41c59faecb0ada48ebeca0933/src/config.rs#L126). 

Is there something I'm missing/amiss with how LeftWM is getting terminals?

**Comment by AethanFoot** [comment]
Ok sorry, I was confused what default_terminals was used for. 
Along the same type of topic, is it possible to set default apps for leftwm that can be used with the config.

**Comment by mautamu** [comment]
Absolutely, it does depend what you mean by default applications. Anything in the config.toml keybind section can be used to tell LeftWM how to launch a program. Suppose for example that I want mod+shift+f to open firefox-developer-edition instead of Firefox, the original looks like: 
```toml
[[keybind]]
command = "Execute"
value = "firefox"
modifier = ["modkey", "Shift"]
key = "f"
```

the modified looks like:
```toml
[[keybind]]
command = "Execute"
value = "firefox-developer-edition"
modifier = ["modkey", "Shift"]
key = "f"
```

This could be the “default,” but only LeftWM will obey that default. If you want other programs (say, an email client) to open Firefox-developer-edition rather than Firefox, you’ll need to set you xdg settings for that. Directions for that are available at 
https://unix.stackexchange.com/questions/77136/xdg-open-default-applications-behavior#107508 and https://stackoverflow.com/questions/41172692/xdg-open-not-open-default-browser#50893809

if you want LeftWM to open the xdg default (which you can, but might not be what you want) you could modify the config.toml like so (note that it requires a file or URL be passed, so some browsers and browser settings will ditch your old tabs running this, but this could be great if you want to open NPR.org with a key press):
```toml
[[keybind]]
command = "Execute"
value = "xdg-open \"https://npr.org/\""
modifier = ["modkey", "Shift"]
key = "f"
```
