### ISSUE TITLE
Problem with AZERTY Keyboard ?

### ISSUE THREAD

**Issue by mikaelmantel** [leftwm/leftwm#188]
Hello,
first of all, thank you for your work on leftwm, this is a great project.
I tried to use it on my laptop with french keyboard layout (azerty) nd I have a problem with the configuration of GotoTag.

By default, with modkey + number, that doesn't work.
Yes because the number key on azerty keyboard does not use the numbers by default. Example :   &é"'(-è_çà)

Ok, so i just modify the config to apply modkey + é (for the tag 2 for exemple).
But this doesn't work too.

I don't know and I don't have the sufficient knowledge of Rust for digging into the code.

Just for the record.

Thank you.

**Comment by mautamu** [comment]
Temporary solution is to use eacute (é):
```toml
[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "eacute"
```

**Comment by midnightexigent** [comment]
@mautamu 

Could you update your comment with the following to provide a convenient copy-paste ? 

```toml
[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "ampersand"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "eacute"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "quotedbl"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "apostrophe"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "parenleft"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "minus"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "egrave"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "underscore"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "ccedilla"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "ampersand"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "eacute"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "quotedbl"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "apostrophe"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "parenleft"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "minus"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "egrave"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "underscore"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "ccedilla"

```
