### ISSUE TITLE
Cant resize windows

### ISSUE THREAD

**Issue by mWalrus** [leftwm/leftwm#195]
Just installed leftwm via AUR and tried setting the keybinds for `IncreaseMainWidth` and `DecreaseMainWidth` but to no avail.

I set these binds in `config.toml`:
```
[[keybind]]
command = "IncreaseMainWidth"
modifier = ["modkey", "Shift"]
key = "u"


[[keybind]]
command = "DecreaseMainWidth"
modifier = ["modkey", "Shift"]
key = "j"
```

After that I tried soft reloading leftwm but nothing changes, also tried rebooting after making changes but that isn't working either.

Am I missing something?

**Comment by mautamu** [comment]
Good afternoon,

It appears that you need to set a value for the percent change you want. Assuming you want 5%, use the following:
```toml
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey", "Shift"]
key = "u"


[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey", "Shift"]
key = "j"
```
