### ISSUE TITLE
Comments requested: Leftwm-theme: Continue with up/down or use theme.toml?

### ISSUE THREAD

**Issue by mautamu** [leftwm/leftwm#201]
Howdy all,

I've been trying to build up the `leftwm-theme` theme manager and have been trying to figure out how to redefine `theme.toml`. Currently, a basic `theme.toml` might look like this:
```toml
border_width = 4
margin = [10, 10]
default_border_color = "#1E272B"
floating_border_color = "#1E272B"
focused_border_color = "#78824B"
```

The dev branch of leftwm/leftwm-theme attempts to add a way to remove the `up` and `down` files in favor of definitions in the `theme.toml` file. Is this something we want to carry forward with the leftwm-theme implementation? The theme.toml proposed in leftwm-theme dev is:
```toml
[global]
name = "mytheme"
dependencies = ["polybar", "dunst"]  # Used to check if required packages are installed in the system

# task.program_name.up sets up the program. The following section will spawn `polybar mybar`
[task.polybar.up]
args = ["mybar"]

# defaults to pkill program name if no down script is provided.
[task.polybar.down]
command = "killall"
args = ["-q", "polybar"]

# if program_name in task.program_name.{up,down} does not match any dependency listed, a command value must be provided.
# paths are relative to the current directory of theme.toml file.
[task.notification.up]
command = "/usr/bin/dunst"
args = ["--config", "configs/dunstrc"]
``` 

I think a few things need modified to maximize install power with respect to leftwm-theme as implemented in leftwm-theme [b27762c0f7ccc30012909908741f2432c52bc03b](https://github.com/leftwm/leftwm-theme/commit/b27762c0f7ccc30012909908741f2432c52bc03b) : 

```toml
border_width = 4 # define these up here for backwards compatibility with leftwm < 0.2.7
margin = [10, 10]
default_border_color = "#1E272B"
floating_border_color = "#1E272B"
focused_border_color = "#78824B"

[global]
name = "mytheme"
description = "A basic theme"
repository = "https://github.com/mautamu/theme"
commit = "*" # pin at a specific version as a "release"
version = "1.0.0"
leftwm_versions = ">2.6.7" # only install on compatible leftwms
dependencies = ["polybar", "dunst"]  # Used to check if required packages are installed in the system

# task.program_name.up sets up the program. The following section will spawn `polybar mybar`
[task.polybar.up]
args = ["mybar"]

# defaults to pkill program name if no down script is provided.
[task.polybar.down]
command = "killall"
args = ["-q", "polybar"]

# if program_name in task.program_name.{up,down} does not match any dependency listed, a command value must be provided.
# paths are relative to the current directory of theme.toml file.
[task.notification.up]
command = "/usr/bin/dunst"
args = ["--config", "configs/dunstrc"]

[task.polybar.install]
packages = {pacman = ["polybar"], apt =["polybar"], dnf = ["polybar"] }
```

Which direction do we want to go with?
