### ISSUE TITLE
Can't use space bar as valid key for key combination

### ISSUE THREAD

**Issue by vladimirlucifer** [leftwm/leftwm#211]
Is this expected behavior? If so, why can I use Return and not Space?

**Comment by mautamu** [comment]
Good morning, this works for me:

```toml
[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey", "Shift"]
key = "space"
```
Not sure why it's "space" and not "Space" though.

Does this work on your copy?
