### ISSUE TITLE
How do I refresh after making a change to one of the theme configs?

### ISSUE THREAD

**Issue by JwanKhalaf** [leftwm/leftwm#212]
First, I'd like to thank you for your hard work, I'm loving LeftWM! DistroTube informed me about it in one of his videos on YouTube.

I have the query mentioned in the title. If I make a change to one of the theme config files, how do I force a refresh so that the changes are picked up?

Right now I'm rebooting, but that is starting to get REAL annoying.

**Comment by lex148** [comment]
Mod+Shift+R should reload the theme.
 
Another option is just re-run the `up` script. 
When I'm working on a theme, I just have a terminal open to the theme directory. when I want to test I just run `./up`

**Comment by VuiMuich** [comment]
and of course one could have this bound to a hotkey:
```toml
[[keybind]]
command = "execute"
value = "$HOME/.config/leftwm/theme/current/up"
modifier = ["modkey", "Shift"]
key = "u"
```
btw: a command to just reload keybinds from the config.toml would be nice as well.
