### ISSUE TITLE
Remember layout by tag

### ISSUE THREAD

**Issue by jwnpoh** [leftwm/leftwm#260]
Is there a way to get LeftWM to remember a different layout for different tags? For eg., I would like tag 1 to be in Monocle and tag 2 to be MainAndVertStack.

It seems like LeftWM's default behaviour is to remember layout by workspace, which is useful for multi-monitor setups but for a single screen, maybe remembering layout by tag is more useful?

Thanks!

**Comment by VuiMuich** [comment]
Currently there is now way to do this.
And I agree, that at least on single-workspace setups tag-centered behaviour would be more intuitive.

I have this on my personal whish-list as well, together with a possibility to assign default workspaces for specific programs, like "browsers" on tag 2, mocp and vlc on tag 6 etc.

**Comment by AethanFoot** [comment]
Should we set this up as a discussion, as personally I feel that per tag layouts feels more natural where you could set a default layout for a tag. However this would be a fundamental change, in the extreme case it could be an option to chose between them, or at least make it default to tag centric with one workspace (however this may become confusing and bloated).

**Comment by VuiMuich** [comment]
> Should we set this up as a discussion, as personally I feel that per tag layouts feels more natural where you could set a default layout for a tag. However this would be a fundamental change, in the extreme case it could be an option to chose between them, or at least make it default to tag centric with one workspace (however this may become confusing and bloated).

+1 on having this in discussions. 
I feel there are several topics, that would live better in the discussion category and not in issues or comments on PRs. 
Especially for some general design questions like this.

**Comment by mautamu** [comment]
If we are to add this to config.toml, one question that comes to mind is whether leftwm should save state or not? E.g. I start leftwm with a tag named Alpha in Monocle layout:
```toml
[[tag]]
name="Alpha"
layout="Monocle"
```
And then change layouts to, for example, Fibonacci. Should config.toml track this change?
```toml
[[tag]]
name="Alpha"
layout="Fibonacci"
```

Another couple of ideas that I've had: perhaps a `leftwm-config` that replaces `leftwm-check`. It would allow us to avoid issues like #188 by providing an interface to capture keypress names as LeftWM knows them (e.g. Modkey + Shift + eacute) and bind them to commands that LeftWM knows. Example excerpt:
```
mau@mau-pc ~> leftwm-config keys
==> 5 Keybinding found:
    [1] Modkey + Shift + X           -> HardReload
    [2] Modkey + Shift + R           -> SoftReload
    [3] Modkey + e                       -> Execute
    [4] XF86XK_MonBrightnesUp -> Execute
    [5] Modkey + Right                -> FocusNextTag
Commands:
    [a] add new keybind
    [#] edit existing keybind as numbered above
    [#/r] remove existing keybind as numbered above
Enter command below: 
==>a
Press the key combinations you would like to use, then hit Return key twice:
Modifiers: modkey, Shift
key: "1"
Returning . . . 
Select Command:
    Execute [x]
Enter value:
    "firefox"
Create keybind Modkey + Shift + F that Executes `firefox`? [y/n]
==> y
==> 6 Keybinding found:
    [1] Modkey + Shift + X           -> HardReload
    [2] Modkey + Shift + R           -> SoftReload
    [3] Modkey + e                       -> Execute
    [4] XF86XK_MonBrightnessUp     -> Execute
    [5] Modkey + Right                -> FocusNextTag
    [6] Modkey + Shift + 1          -> Execute
Commands:
    [a] add new keybind
    [#] edit existing keybind as numbered above
    [#/r] remove existing keybind as numbered above
Enter command below: 
==>6
Commands:
    [1] Edit Command: Execute
    [2] Edit Value: `firefox`
    [3] Edit Keybinding: Modkey + Shift + 1
    [4] Delete keybinding
    [5] Return
...
```

leftwm-config could also change tag information, maybe leftwm-config tags:
```
mau@mau-pc ~> leftwm-config tags
==> 5 Tags found:
    [1] Alpha (Fibonacci)
          Programs: `firefox`, `chromium`, `brave`, `/usr/bin/waterfox`
    [2] Bravo (Monocle)
          Programs: `thunderbird`
    [3] Charlie (RightMainAndVertStack)
          Programs: `alacritty`, `blender`, `inkscape`
    [4] Delta (None)
    [5] Echo (None)

Commands:
    [a] add new tag
    [#] edit existing tag as numbered above
    [#/r] remove existing tag as numbered above
```

Another long-term thing I think we might consider as part of #201 might be to be able to tell LeftWM to use command output as input (e.g. for using pywal to theme borders, or maybe to implement #226) like:
```toml
border_width = 4 # define these up here for backwards compatibility with leftwm < 0.2.7
margin = [10, 10]
default_border_color = {exec = "head -n 1 ~/.cache/wal/sequences"}
floating_border_color = {exec = "tail -n 1 ~/.cache/wal/sequences" }
focused_border_color = "#78824B"
```

Not sure exactly the best way to have leftwm go and update all of those execs, so if anyone has some ideas or thoughts they'd be much appreciated!

**Comment by mautamu** [comment]
Do we also want to maybe allow for a theme to specify different color schemes eg:
```toml
#Theme.toml
[[scheme.default]]
default_border_color = {exec = "head -n 1 ~/.cache/wal/sequences"}
floating_border_color = {exec = "tail -n 1 ~/.cache/wal/sequences" }
focused_border_color = "#78824B"

[[scheme.browsers]]
default_border_color = "#0000ff"
floating_border_color = "#0000fc"
focused_border_color = "#0000fc"

[[scheme.work]]
default_border_color = "#ff0000"
floating_border_color = "#fc0000"
focused_border_color = "#fc0000"
```

Which could then be specified in the config.toml?

```toml
#Config.toml
[[tag]]
name="Alpha"
layout="Monocle"
scheme="browsers"
```

I think we'd likely want to publish a list of schemes that themes could/should support. Thoughts?

**Comment by AethanFoot** [comment]
> If we are to add this to config.toml, one question that comes to mind is whether leftwm should save state or not? E.g. I start leftwm with a tag named Alpha in Monocle layout:
> 
> ```toml
> [[tag]]
> name="Alpha"
> layout="Monocle"
> ```
> 
> And then change layouts to, for example, Fibonacci. Should config.toml track this change?
> 
> ```toml
> [[tag]]
> name="Alpha"
> layout="Fibonacci"
> ```
I would say no to saving the state past hard reload, the value set in the config should be the one you want to fall back to when you start leftwm or have a command which will swap the layout to the default (we could maybe have a keybinding that allows the user to save the current layout to default, but that might be awkward code for a feature rarely used).

> Another couple of ideas that I've had: perhaps a leftwm-config that replaces leftwm-check. It would allow us to avoid issues like #188 by providing an interface to capture keypress names as LeftWM knows them (e.g. Modkey + Shift + eacute) and bind them to commands that LeftWM knows. 

This idea is exciting especially with the shortcut capture, as personally the quality of life this provides is above everything else as trying to find out all the key ids and such is most annoying especially I would of thought for newer users. Then allowing the user to setup there config for this would give a safety net if they are new to wm's or linux.
>Not sure exactly the best way to have leftwm go and update all of those execs, so if anyone has some ideas or thoughts they'd be much appreciated!

Thinking about this, would it be possible to create a ThemeReload command which would be a step down from SoftReload. Either way I feel this should be manually done by the user, as I wouldn't think the colour scheme would be changed too often (Unless we asynchronously check the config files and files pointed to by execs for change and automatically update, but this would be overkill). That also depends on the type of execs they would be as well, I can't think of anything that would be used that needs updating constantly (Unless you implement a script which outputs different colours based on the weather outside, on second thought that would be quite cool)

The schemes idea is cool and would add an interesting layer to the theming, however I think this should be utilised for all the current theming options, e.g.:
```toml
#Theme.toml
[[scheme.default]]
default_border_color = {exec = "head -n 1 ~/.cache/wal/sequences"}
floating_border_color = {exec = "tail -n 1 ~/.cache/wal/sequences" }
focused_border_color = "#78824B"

[[scheme.browsers]]
default_border_color = "#0000ff"
floating_border_color = "#0000fc"
focused_border_color = "#0000fc"

[[scheme.work]]
default_border_color = "#ff0000"
floating_border_color = "#fc0000"
focused_border_color = "#fc0000"

[[options.default]]
scheme = "default"
border_width = 4 # define these up here for backwards compatibility with leftwm < 0.2.7
margin = [10, 10]

[[options.work]]
scheme = "work"
border_width = 1 # define these up here for backwards compatibility with leftwm < 0.2.7
margin = [0, 0]
...
#Config.toml
[[tag]]
name = "Alpha"
layout = "Monocle"
options = "work"
...
```
