### ISSUE TITLE
Can I toggle space?

### ISSUE THREAD

**Issue by Mirocif** [leftwm/leftwm#280]
Just a noob here.
Can I toggle the space between the windows or just decrease o increase?

**Comment by rebuilt** [comment]
The setting you want is in the theme.toml file.  It's not a configuration of leftwm per se, but you'll find it inside the current theme folder you're using.  
```bash
cd ~/.config/leftwm/themes/current
nvim theme.toml
```
Then change or add a line for:
```bash 
margin = 5
```
Margin is measured in pixels.

**Comment by VuiMuich** [comment]
With #259 just merged you have an option to apply a multiplier to the configured margin.
You need to use the git-version, since I don't know if the 0.2.7 release is gonna be patched with this merge.

This command-snippet gives an Idea what config possibilities there are:
```toml
[[keybind]]
command = "SetMarginMultiplier"
# value takes float as multiplier
# use "0.0" for no margins at all
# use "1.0" to reset
value = "2.5"
moddifier = ["modkey"]
key = "m"
```
