### ISSUE TITLE
More than 9 tags?

### ISSUE THREAD

**Issue by hrehfeld** [leftwm/leftwm#287]
Is it possible to increase the number of tags?

```
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]

[[keybind]]
command = "GotoTag"
value = "0"
modifier = ["modkey"]
key = "0"

[[keybind]]
command = "MoveToTag"
value = "0"
modifier = ["modkey", "Shift"]
key = "0"
```
doesn't seem to do the trick.

**Comment by mautamu** [comment]
Yeah, just add however many you like:
```toml
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "alpha", "bravo", "charlie"]
```

As for why the keybind is likely not working, the keybinds reference position rather than name (a bit confusing when the default tags are 1, 2, 3.... ). Are you using a numpad? If not:
```toml
[[keybind]]
command = "GotoTag"
value = "10"
modifier = ["modkey"]
key = "0"

[[keybind]]
command = "MoveToTag"
value = "10"
modifier = ["modkey", "Shift"]
key = "0"
```
If so:
```toml
[[keybind]]
command = "GotoTag"
value = "10"
modifier = ["modkey"]
key = "KP_0"

[[keybind]]
command = "MoveToTag"
value = "10"
modifier = ["modkey", "Shift"]
key = "KP_0"
```
