### ISSUE TITLE
Add Binding Modes

### ISSUE THREAD

**Issue by mautamu** [leftwm/leftwm#318]
Per #317, LeftWM might consider adding "Binding Modes" to the keybinds section.
Most likely the current structure:
```
[global]
|    [[keybind]]
```
Could be made into 
```
[global]
[bindings]
|    [[keybind]]
```
An alternative might be to do the following:
```toml
modes = [0, 1, 2] #alternatively, ["0", "1", "2"]
[[keybind]]
command = "Execute"
value = "rofi -show drun -theme ~/.config/leftwm/themes/current/rofi/rofi.rasi"
modifier = ["modkey"]
key = "e"
modes = [0, 2] #alternatively ["0","2"]
```

Thoughts?
