### ISSUE TITLE
Doesn't integrate with alacritty that runs tmux

### ISSUE THREAD

**Issue by winston0410** [leftwm/leftwm#415]
**Describe the bug**

leftwm functions normally with alacritty. But when alacritty runs tmux, switching workspaces using `Mod-<number>` doesn't work. It will freeze tmux, which doesn't accept any input and output, but tmux will remain on the screen.

As it will freeze tmux, I am sure that the keypress is not eaten up by tmux.

**To Reproduce**
1. Use the following alacritty config
```yml
---
shell:
  program: /run/current-system/sw/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main
```
2. Go to workspace two with `Mod-2`, and use dmenu to start chromium there.

3. Go back to workspace one with `Mod-1`, and use `Mod-Shift-Enter` to start alacritty that runs tmux

4. Press `Mod-2`. Tmux will now freeze and now accpets any input, but the screen will remain in tmux, instead of switching to chromium

**Expected behavior**
I expect I can switch pane correctly

**Screenshots**

**Environment:**
 - OS/Distro: NixOS 21.05
 - Output of `leftwm-check` hm command not found. I am not self-build leftwm with cargo, so I don't get that command.

**Additional context**

**Comment by VuiMuich** [comment]
> Output of leftwm-check hm command not found. I am not self-build leftwm with cargo, so I don't get that command

Do you have any other source for providing a leftwm version number? (Package Info?)
It looks like the package might be out of date if you don't have leftwm-check. For example the latest AUR leftwm-bin should include this command afaik.

Currently on mobile but will check later if I can reproduce in Manjaro.

**Comment by VuiMuich** [comment]
With `LeftWM git hash: 72b2f51` on a up to date manjaro everything works as expected.
TBF I started `tmux` not directly, but from my interactive shell `fish`, can you verify if it helps to attatch to a tmux session form another shell and/or another terminal emulator?
Also can you double check, that you don't have any overlapping key bindings?

As 0.2.8 released just 2 hours ago, you might want to observe if the package maintainer will update quickly again, or nudge him to push an update.

**Comment by AethanFoot** [comment]
Looking at the nix packages leftwm is on 0.2.7, however leftwm-check was not added to the package build. Will open an issue later saying about the extra utilities and the version bump.
Thanks.

**Comment by winston0410** [comment]
@VuiMuich Hm I tried just now, launching alacritty with `bash` instead, but I cannot switch to another workspace as well in bash. I am wondering if alacritty is blocking to keybindings, but I have not set any bindings in my own alacritty set up.

**Comment by winston0410** [comment]
I have just experimented with using `fish` in alacritty as well, but it didn't work.

**Comment by VuiMuich** [comment]
Are you using `Super` or `Alt` as `Mod`?
Maybe try another terminal emulator like `kitty`, `xterm` or `st`. 
By default `alacritty` shouldn't have conflicting key binds as well, but I don't know a lot of `nix-os`. 
Is there possibly another tool handling key commands? Something like `sxhkd` or similar?

**Comment by winston0410** [comment]
I have just tried out again, and it seems like the issue should be Alacritty. But by default alacritty should not set any keybinding for me.

Also I have checked that I don't have any service that capture keypress like `sxhkd`, so I guess the issue must be coming from Alacritty

Closing this now.

**Comment by winston0410** [comment]
I notice something, for the terminal that would work properly( `kitty` and `wezterm`), they all have a thin red line surrounding it, but not with `alacritty`. What does that imply?

**Comment by AethanFoot** [comment]
Is it possible to have your alacritty conf to look through and test (wont be able to test till tomorrow). When testing other terminals did you open them with tmux aswell?
Thanks.

**Comment by winston0410** [comment]
Sure, this is my current config

```yml
---
shell:
  program: /run/current-system/sw/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main

# shell:
#   program: /usr/local/bin/zsh
#   args:
#     - --login
env:
  # TERM: xterm-256color
  TERM: xterm-256color
  LC_ALL: en_US.UTF-8
font:
  normal:
    family: "Hack Nerd Font"
  size: 27.0
  use_thin_strokes: true
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true
# mouse:
#   url:
#     launcher:
#       # This depends on your OS, on Mac it’s `open`
#       program: open
#     modifiers: Command
schemes:
  edge_dark_def: &edge_dark_def
    primary:
      background: "0x2c2e34"
      foreground: "0xc5cdd9"

    normal:
      black: "0x3e4249"
      red: "0xec7279"
      green: "0xa0c980"
      yellow: "0xdeb974"
      blue: "0x6cb6eb"
      magenta: "0xd38aea"
      cyan: "0x5dbbc1"
      white: "0xc5cdd9"

      bright:
        black: "0x3e4249"
        red: "0xec7279"
        green: "0xa0c980"
        yellow: "0xdeb974"
        blue: "0x6cb6eb"
        magenta: "0xd38aea"
        cyan: "0x5dbbc1"
        white: "0xc5cdd9"
  # Default colors
  tokyonight_night: &tokyonight_night # Default colors
    primary:
      background: "0x1a1b26"
      foreground: "0xc0caf5"

    # Normal colors
    normal:
      black: "0x15161E"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xa9b1d6"

    # Bright colors
    bright:
      black: "0x414868"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xc0caf5"

    indexed_colors:
      - { index: 16, color: "0xff9e64" }
      - { index: 17, color: "0xdb4b4b" }
  tokyonight_storm: &tokyonight_storm
    primary:
      background: "0x24283b"
      foreground: "0xc0caf5"

    # Normal colors
    normal:
      black: "0x1D202F"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xa9b1d6"

    # Bright colors
    bright:
      black: "0x414868"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xc0caf5"

    indexed_colors:
      - { index: 16, color: "0xff9e64" }
      - { index: 17, color: "0xdb4b4b" }
# colors: *edge_dark_def
colors: *tokyonight_night
# colors: *tokyonight_storm
```
