### ISSUE TITLE
Unable to set keymapping with Tab as key

### ISSUE THREAD

**Issue by winston0410** [leftwm/leftwm#417]
**Describe the bug**
I want to set a key mapping for `Command-Tab` for switching workspace. I have remapped `Ctrl` to `Command`.

This is my key mapping:

```toml
[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey"]
key = "Tab"
```

**To Reproduce**
1. Use the following keymapping in `~/.config/leftwm/config.toml`:

```toml
[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey"]
key = "Tab"
```

2. Click the mapping. Nothing happens.

**Expected behavior**

To be able to trigger "MoveToLastWorkspace"

**Environment:**
 - OS/Distro: NixOS 21.05
 - Output of `leftwm-check`

**Additional context**
I have looked up this [issue](https://github.com/leftwm/leftwm/issues/211), and I have used `xev` to check for the output of my key. This is the output for me to click on `Tab`

```
[hugosum@nixos:~/.config/leftwm]$ nix-shell -p xorg.xev

[nix-shell:~/.config/leftwm]$ xev -event keyboard
Outer window is 0x1200001, inner window is 0x1200002

KeyRelease event, serial 28, synthetic NO, window 0x1200001,
    root 0x7ad, subw 0x0, time 1451921, (228,829), root:(1519,840),
    state 0x0, keycode 23 (keysym 0xff09, Tab), same_screen YES,
    XLookupString gives 1 bytes: (09) " "
    XFilterEvent returns: False
```
As it is `Tab` in the output, I think I have get the key correctly.

**Comment by mautamu** [comment]
Curiously, this works:
```toml
[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Tab"
```

While this does not work:
```toml
[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey"]
key = "g"
```

This *might* be an issue with MoveToLastWorkspace. `leftwm-check` states that everything is OK, so it's not a spelling issue.

**Comment by winston0410** [comment]
Hm but I have tried `MoveToLastWorkspace` with the default binding, and it is working correctly. No hunch what went wrong.

**Comment by mautamu** [comment]
Hmm, does the 
```toml
[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Tab"
```
work for you?

I am unable to get MoveToLastWorkspace to work at all, either with the default keybindings or with custom ones (admittedly I don't use it).

**Comment by VuiMuich** [comment]
> I don't have the ability to really test if MoveToLastWorkspace works, as I only have one workspace and monitor.

For testing scenarios like this I use this on my laptop:
```toml
[[workspaces]]
y = 0
x = 0
height = 1440
width = 1280

[[workspaces]]
y = 0
x = 1280
height = 1440
width = 1280
```
It's a bit awkward, but sufficient for checking corner cases.

And with that I can get 
```toml
[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey"]
key = "Tab"
```
to work properly.

@winston0410 is `leftwm command MoveTo LastWorkspace` working for you?
