### ISSUE TITLE
Volume and Brightness Keys don't work

### ISSUE THREAD

**Issue by Msouza91** [leftwm/leftwm#431]
Usually one has to set up this kind of stuff, but it seems like you guys have tried to map most of it, the brightness control of the notebook backlight works, but volume up and down or brightness don't, nor does the mute key, but the airplane mode key works, what could be the problem? Is it on my end? It used to work fine on gnome. Tried setting up a kb shortcut for pactl, but altough the command working when I type it on the terminal, when I try to add them as a shortcut on my config the file gets rejected and I load the default config map again.

**Comment by VuiMuich** [comment]
Welcome adventurer!
I believe some of your buttons working is still an artifact of another setup of DE/WM (Gnome still installed?), as the default config generated at first launch of leftwm should only contain 'internal' commands with the two exceptions of Execute `terminal` and `dmenu`.
[Here](https://github.com/leftwm/leftwm/wiki/Config#keybind) you can find an example of how to bind commands that work on the terminal to keys as well as a list of all keys leftwm can handle.
You can use `xev -event keyboard` to check out the keys names.
When you edited your config you can use `leftwm check` to figure out whats breaking your config.

If you need further help please give us a bit more info about your setup: your OS, where did you install leftwm from? How do you launch leftwm? etc.

**Comment by winston0410** [comment]
I have actually tried to do the same thing today, trying to map `F1` to light up and `F2` to light down through `leftwm` and get rid of `sxhkd`. This is my config but they are not working, I guess those keys are not handled.

I am unable to get any log yet, so I am not sure.

```toml
[[keybind]]
command = "Execute"
value = "light -U 2"
modifier = []
key = "XF86MonBrightnessDown"

[[keybind]]
command = "Execute"
value = "light -A 2"
modifier = []
key = "XF86MonBrightnessUp"
```
