### ISSUE TITLE
leftwm 0.2.9 doesn't respect border width configuration

### ISSUE THREAD

**Issue by winston0410** [leftwm/leftwm#579]
**Describe the bug**
Updated to 0.2.9 today, and I found out that the border appeared despite I have set its width to 0. I can confirm that the `up` script has been called correctly, so I suspect it is a bug introduced in 0.2.9

**To Reproduce**
1. Make a `theme.toml` like this in `$HOME/.config/leftwm/themes/current/theme.toml

```toml
# Use the same color from my website
default_border_color = '#feebb3'
focused_border_color = '#fcbe03'
border_width = 0
margin = 10
workspace_margin = 0

[[gutter]]
side = "Top"
value = 20

[[gutter]]
side = "Left"
value = 10

[[gutter]]
side = "Right"
value = 10

[[gutter]]
side = "Bottom"
value = 10
```

2 `pkill leftwm` to restart it and see the result.

**Expected behavior**
To not have border

**Screenshots**
![1637261070](https://user-images.githubusercontent.com/59228178/142477402-d770c20e-baec-4f60-b9f6-6121812450b7.jpg)

**Environment:**
 - OS/Distro: NixOS
 - Output of `leftwm-check`:
 
 ```
❯ leftwm-check
:: LeftWM version: 0.2.9
:: LeftWM git hash: NONE
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```

**Additional context**
