### ISSUE TITLE
Add spawn_as_sticky option to window rules (eg. for scratchpad)

### ISSUE THREAD

**Issue by CMurtagh-LGTM** [leftwm/leftwm#662]
Hi,
Would it be possible to add the ability to set a scratchpad to be sticky when its launched.

**Comment by AethanFoot** [comment]
There is a ToggleSticky command e.g.
```toml
[[keybind]]
command = "ToggleSticky"
modifier = ["modkey"]
key = "v"
```
which can applied to any window.
