### ISSUE TITLE
add support for drop-down terminal

### ISSUE THREAD

**Issue by ibootstrapper** [leftwm/leftwm#759]
Terminal such as xfce4-terminal can start in `drop-down` mode via the `--drop-down` argument. 

This opens the terminal at the top center of the screen as a modal on top of all other windows. 

This behavior can be seen on bspwm or I3 as an example. 

In leftwm the window just open as a normal window.

**Comment by mike-lloyd03** [comment]
I've found that the [scratchpad](https://github.com/leftwm/leftwm/wiki/Config#scratchpads) feature works pretty good to replace my need for a dropdown terminal.

I use alacritty and have LeftWM configured as such:
```toml
[[scratchpad]]
name = "Alacritty"
value = 'WINIT_X11_SCALE_FACTOR=1 alacritty -t "Alacritty - Scratch" -o window.opacity=0.8 -e bash -c "tmux a -t scratch || tmux \"new-session;\" rename-session scratch"'
x = 0.05
y = 35
height = 0.50
width =  0.9
```

This launches alacritty and directs tmux to switch to a session called "scratch" or if it doesn't exist, create it.
