### ISSUE TITLE
Windows spawned in non-visible workspaces should not get focus

### ISSUE THREAD

**Issue by carrascomj** [leftwm/leftwm#760]
**Describe the bug**
When a window rule makes a window appear in a non-visible workspace - that is, in a workspace which is not being displayed in any monitor - the user loses focus of the current window.

**To Reproduce**
1. Add this to your config.

```toml
window_rules = [ 
  {window_class = "Navigator", spawn_on_tag = 8},
]

[[keybind]]
command = "Execute"
value = "firefox"
modifier = ["modkey"]
key = "b"
```
3. Put all monitors in workspaces that are not the 8th one.
4. Reload `leftwm`.
5. Open a window (wait for focus) and press Super-B.
6. You have lost focus of the window.

**Expected behavior**
The user should not lose focus. Possible configurations would include to be able to jump the workspace where the window opened instead but I don't think the focus should be lost to a non-visible window in any case.

**Environment:**
 - OS/Distro: 5.17.4-arch1-1
 - Output of `leftwm-check`

```
:: LeftWM version: 0.3.0
:: LeftWM git hash: c0fcf84
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme O
```
