### ISSUE TITLE
`MoveWindowToNextWorkspace` makes `FocusWorkspaceNext` not usable

### ISSUE THREAD

**Issue by TornaxO7** [leftwm/leftwm#785]
**Describe the bug**
I have two monitors, each of them has their own workspace. If I do `MoveWindowToNextWorkspace` then I'm not able to switch the focus of my workspace with the `FocusWorkspaceNext` command.

**To Reproduce**

Here are the relevant code-pieces of my `~/.config/leftwm/config.toml`:

<details>

```toml
modkey = "Mod1"
mousekey = "Mod1"

disable_current_tag_swap = true
disable_tile_drag = false
disable_window_snap = true

focus_behaviour = "Sloppy"
focus_new_windows = true
sloppy_mouse_follows_focus = true

margin = 0
workspace_margin = 0

[[workspaces]]
y = 0
x = 0
width = 1920
height = 1080
id = 0

[[workspaces]]
y = 0
x = 1920
width = 1920
height = 1080
id = 1

tags = ["1", "2", "3", "4", "5", "6"]

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["Mod4"]
key = "e"

[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["Mod4"]
key = "i"
```

</details>

Now open up two windows in each workspace and press `Mod4` + `i` to move the window to the other workspace and then press `Mod4` + `e`.

**Expected behavior**
I expected to be able to switch the focus of my workspace.

**Screenshots**
I don't think that those are necessary here but if you insist to have some, then you're free to say that to me.

**Environment:**
 - OS/Distro: Arch Linux
 - Output of `leftwm-check`:

<details>

```
:: LeftWM version: 0.3.0
:: LeftWM git hash: 16b8a85
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

</details>
