### ISSUE TITLE
[Feature] Add optional list of requried packages for a theme

### ISSUE THREAD

**Issue by Giftzwerg02** [leftwm/leftwm#818]
Since LeftWM seperates general configuration and theming it makes it easier for users to plug-and-play with publicly available themes. To further improve the user experience (by possibly cutting down on troubleshooting-time), a publisher should be able to _configure_ (instead of just hinting at it in a `README`) which packages a user should have to properly use their theme. These could be written inside the `theme.toml` file:
```toml
[[req_packages]]
name = "polybar"
version = "^3.6.3"

[[req_packages]]
name = "rofi"
version = "1.7.4"
```
If these requirements aren't met, a descriptive error should be displayed, explaining that some packages are missing. In case a user doesn't care about these requirements they can simply manually remove these from the given `theme.toml` file.
