### ISSUE TITLE
Shortcuts command not working as expected.

### ISSUE THREAD

**Issue by NicTanghe** [leftwm/leftwm#855]
### Describe the enhancement

Im having problems configuring shortcuts i don`t c what is causing it to break

I`ve tried adding
```toml
[[keybind]]
command = "ToggleFullScreen"
value = ""
modifier = ["modkey","shift"]
key = "f"

[[keybind]]
command = "ToggleScratchPad"
value = "spotify" # Name set for the scratchpad
modifier = ["modkey"]
key = "p"


[[keybind]]
command = "Execute"
value = "/home/ntanghe/scripts/houdini.sh"
modifier = ["modkey"]
key = "h"

```
to config.toml but these didn`t work.

also doesn`t seem to work.

### How important is this enhancement to you?

Would be nice to have

### How important do you think is this enhancement for the average LeftWM user?

Their workflow is likely impaired without it
